In [1143]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [1144]:
df1 = pd.read_csv('train.csv')
df2 = pd.read_csv('test.csv')

df1.shape, df2.shape

((1460, 81), (1459, 80))

In [1145]:
df1.isna().sum()[df1.isna().sum() > 0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtFinType1      37
BsmtCond          37
BsmtQual          37
MasVnrArea         8
Electrical         1
dtype: int64

In [1146]:
df1.drop([col for col in df1.columns if df1[col].isna().sum()>500],axis=1,inplace=True)
df1.shape

(1460, 75)

In [1147]:
df2.isna().sum()[df2.isna().sum() > 0].sort_values(ascending=False)

PoolQC          1456
MiscFeature     1408
Alley           1352
Fence           1169
MasVnrType       894
FireplaceQu      730
LotFrontage      227
GarageCond        78
GarageYrBlt       78
GarageQual        78
GarageFinish      78
GarageType        76
BsmtCond          45
BsmtExposure      44
BsmtQual          44
BsmtFinType1      42
BsmtFinType2      42
MasVnrArea        15
MSZoning           4
BsmtFullBath       2
BsmtHalfBath       2
Functional         2
Utilities          2
GarageCars         1
GarageArea         1
TotalBsmtSF        1
KitchenQual        1
BsmtUnfSF          1
BsmtFinSF2         1
BsmtFinSF1         1
Exterior2nd        1
Exterior1st        1
SaleType           1
dtype: int64

In [1148]:
df2.drop([col for col in df2.columns if df2[col].isna().sum()>500],axis=1,inplace=True)
df2.shape

(1459, 74)

In [1149]:
df1.dropna(inplace=True)

In [1150]:
# add SalePrice column with any value to concat the 2 datasets
df2['SalePrice'] = -1

In [1151]:
df1.shape, df2.shape

((1094, 75), (1459, 75))

In [1152]:
df = pd.concat([df1, df2], axis=0)
df.shape

(2553, 75)

In [1153]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [1154]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [1155]:
df.drop(columns=["Id"], inplace=True)
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [1156]:
object_columns = [col for col in df.columns if df[col].dtype == 'object']
numeric_columns = [col for col in df.columns if df[col].dtype != 'object']

In [1157]:
for col in object_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

df.isnull().sum()[df.isna().sum()>0].sort_values(ascending=False)

Series([], dtype: int64)

In [1158]:
for col in object_columns:
    print(df[col].value_counts())
    print('-'*30)

MSZoning
RL         1968
RM          415
FV          128
C (all)      23
RH           19
Name: count, dtype: int64
------------------------------
Street
Pave    2543
Grvl      10
Name: count, dtype: int64
------------------------------
LotShape
Reg    1694
IR1     785
IR2      61
IR3      13
Name: count, dtype: int64
------------------------------
LandContour
Lvl    2302
HLS     114
Bnk      99
Low      38
Name: count, dtype: int64
------------------------------
Utilities
AllPub    2553
Name: count, dtype: int64
------------------------------
LotConfig
Inside     1911
Corner      435
CulDSac     126
FR2          67
FR3          14
Name: count, dtype: int64
------------------------------
LandSlope
Gtl    2441
Mod     104
Sev       8
Name: count, dtype: int64
------------------------------
Neighborhood
NAmes      391
CollgCr    239
OldTown    222
Somerst    171
NridgHt    163
Edwards    159
Gilbert    135
Sawyer     121
SawyerW    110
NWAmes     103
Mitchel     95
Crawfor     93
BrkSide     92
IDOTRR      83
Timber      63
NoRidge     63
StoneBr     46
SWISU       42
MeadowV     30
BrDale      29
ClearCr     27
Blmngtn     25
NPkVill     21
Veenker     20
Blueste     10
Name: count, dtype: int64
------------------------------
Condition1
Norm      2201
Feedr      135
Artery      86
RRAn        48
PosN        29
RRAe        25
PosA        16
RRNn         8
RRNe         5
Name: count, dtype: int64
------------------------------
Condition2
Norm      2526
Feedr       12
Artery       5
PosN         4
PosA         4
RRNn         2
Name: count, dtype: int64
------------------------------
BldgType
1Fam      2130
TwnhsE     203
Twnhs       88
Duplex      81
2fmCon      51
Name: count, dtype: int64
------------------------------
HouseStyle
1Story    1285
2Story     773
1.5Fin     277
SLvl       106
SFoyer      69
2.5Unf      22
1.5Unf      15
2.5Fin       6
Name: count, dtype: int64
------------------------------
RoofStyle
Gable      2012
Hip         495
Gambrel      21
Flat         12
Mansard      10
Shed          3
Name: count, dtype: int64
------------------------------
RoofMatl
CompShg    2520
Tar&Grv      17
WdShngl       7
WdShake       6
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64
------------------------------
Exterior1st
VinylSd    932
MetalSd    402
HdBoard    371
Wd Sdng    354
Plywood    177
CemntBd    110
BrkFace     73
WdShing     50
AsbShng     38
Stucco      36
BrkComm      5
CBlock       2
Stone        1
ImStucc      1
AsphShn      1
Name: count, dtype: int64
------------------------------
Exterior2nd
VinylSd    923
MetalSd    402
Wd Sdng    339
HdBoard    337
Plywood    210
CmentBd    111
Wd Shng     71
BrkFace     41
Stucco      41
AsbShng     33
Brk Cmn     21
ImStucc     14
AsphShn      3
Stone        3
CBlock       3
Other        1
Name: count, dtype: int64
------------------------------
ExterQual
TA    1538
Gd     886
Ex     101
Fa      28
Name: count, dtype: int64
------------------------------
ExterCond
TA    2229
Gd     257
Fa      54
Ex      11
Po       2
Name: count, dtype: int64
------------------------------
Foundation
PConc     1179
CBlock    1047
BrkTil     287
Slab        25
Stone       11
Wood         4
Name: count, dtype: int64
------------------------------
BsmtQual
TA    1164
Gd    1054
Ex     250
Fa      85
Name: count, dtype: int64
------------------------------
BsmtCond
TA    2346
Gd     108
Fa      95
Po       4
Name: count, dtype: int64
------------------------------
BsmtExposure
No    1729
Av     371
Gd     239
Mn     214
Name: count, dtype: int64
------------------------------
BsmtFinType1
Unf    806
GLQ    754
ALQ    371
Rec    260
BLQ    226
LwQ    136
Name: count, dtype: int64
------------------------------
BsmtFinType2
Unf    2251
Rec      88
LwQ      76
BLQ      60
ALQ      46
GLQ      32
Name: count, dtype: int64
------------------------------
Heating
GasA    2521
GasW      25
Grav       4
Wall       2
OthW       1
Name: count, dtype: int64
------------------------------
HeatingQC
Ex    1346
TA     727
Gd     407
Fa      70
Po       3
Name: count, dtype: int64
------------------------------
CentralAir
Y    2394
N     159
Name: count, dtype: int64
------------------------------
Electrical
SBrkr    2346
FuseA     161
FuseF      38
FuseP       7
Mix         1
Name: count, dtype: int64
------------------------------
KitchenQual
TA    1286
Gd    1019
Ex     196
Fa      52
Name: count, dtype: int64
------------------------------
Functional
Typ     2383
Min2      61
Min1      55
Mod       30
Maj1      15
Maj2       8
Sev        1
Name: count, dtype: int64
------------------------------
GarageType
Attchd     1609
Detchd      717
BuiltIn     161
Basment      32
2Types       22
CarPort      12
Name: count, dtype: int64
------------------------------
GarageFinish
Unf    1188
RFn     722
Fin     643
Name: count, dtype: int64
------------------------------
GarageQual
TA    2402
Fa     122
Gd      21
Po       5
Ex       3
Name: count, dtype: int64
------------------------------
GarageCond
TA    2456
Fa      70
Po      13
Gd      11
Ex       3
Name: count, dtype: int64
------------------------------
PavedDrive
Y    2324
N     174
P      55
Name: count, dtype: int64
------------------------------
SaleType
WD       2187
New       233
COD        75
ConLD      22
CWD        12
ConLI       7
ConLw       7
Con         5
Oth         5
Name: count, dtype: int64
------------------------------
SaleCondition
Normal     2084
Partial     239
Abnorml     159
Family       44
Alloca       18
AdjLand       9
Name: count, dtype: int64
------------------------------

In [1159]:
df.drop(columns=['Utilities'], inplace=True)

In [1160]:
df.shape

(2553, 73)

In [1161]:
object_columns.pop(object_columns.index('Utilities'))

'Utilities'

In [1162]:
'Utilities' in object_columns

False

In [1163]:
df = pd.get_dummies(df, columns=object_columns, drop_first=True)
df.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,...,False,False,False,False,True,False,False,False,True,False
1,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,...,False,False,False,False,True,False,False,False,True,False
2,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,...,False,False,False,False,True,False,False,False,True,False
3,70,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,...,False,False,False,False,True,False,False,False,False,False
4,60,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,...,False,False,False,False,True,False,False,False,True,False

In [1164]:
train_data, test_data = df[df['SalePrice'] != -1], df[df['SalePrice'] == -1]

In [1165]:
test_data['SalePrice'].value_counts()

SalePrice
-1    1459
Name: count, dtype: int64

In [1166]:
test_data.drop(columns=['SalePrice'], inplace=True)

<ipython-input-1166-500474b48582>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data.drop(columns=['SalePrice'], inplace=True)

In [1167]:
test_data.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,False,False,False,False,True,False,False,False,True,False
1,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,False,False,False,False,True,False,False,False,True,False
2,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,False,False,False,False,True,False,False,False,True,False
3,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,False,False,False,False,True,False,False,False,True,False
4,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,False,False,False,False,True,False,False,False,True,False

In [1168]:
X = train_data.drop(['SalePrice'], axis=1)
y = train_data['SalePrice']

In [1169]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)
test_data = sc.transform(test_data)

In [1170]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [1171]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
mean_squared_error(y_test, y_pred)

685775607.110193

In [1172]:
from xgboost import XGBRegressor

model = XGBRegressor(n_estimators=1000, learning_rate=0.1, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mean_squared_error(y_test, y_pred)

726073792.0

In [1174]:
pred = model.predict(test_data)

output = pd.DataFrame({'Id': df2.Id, 'SalePrice': pred})
output.to_csv('submission.csv', index=False)